// /**
//  * This code was generated by v0 by Vercel.
//  * @see https://v0.dev/t/VHELXzABxgN
//  */
// import { Input } from "@/components/ui/input"
// import { Button } from "@/components/ui/button"

// export function achatUi() {
//   return (
//     <div className="w-full max-w-[400px] rounded-lg border border-gray-200 dark:border-gray-800 bg-opacity-10 bg-blur-md bg-white dark:bg-gray-800/10">
//       <div className="flex flex-1 flex-col overflow-hidden">
//         <div className="flex-1 overflow-y-auto">
//           <div className="p-4 space-y-4">
//             <div className="flex flex-col items-center space-y-2">
//               <img
//                 alt="Avatar"
//                 className="rounded-full"
//                 height="40"
//                 src="/placeholder.svg"
//                 style={{
//                   aspectRatio: "40/40",
//                   objectFit: "cover",
//                 }}
//                 width="40"
//               />
//               <p className="text-xs text-gray-500 dark:text-gray-400">You're chatting with Shad</p>
//             </div>
//             <div className="rounded-xl bg-gray-100/50 p-4 text-sm dark:bg-gray-800/50">
//               Hi there! How can I help you today?
//             </div>
//             <div className="rounded-xl bg-gray-100/50 p-4 text-sm dark:bg-gray-800/50">
//               I can assist you with documentation, troubleshooting, and more.
//             </div>
//             <div className="rounded-xl bg-gray-100/50 p-4 text-sm dark:bg-gray-800/50">
//               Feel free to ask me anything!
//             </div>
//             <div className="flex flex-col space-y-2">
//               <div className="rounded-xl bg-gray-100/50 p-4 text-sm dark:bg-gray-800/50 self-start">
//                 How do I deploy my app to the web?
//               </div>
//               <div className="rounded-xl bg-gray-100/50 p-4 text-sm dark:bg-gray-800/50 ml-auto">
//                 To deploy your app, you can use the Vercel platform. Simply create a new project, link your Git
//                 repository, and Vercel will handle the rest!
//               </div>
//             </div>
//           </div>
//         </div>
//         <div className="border-t  border-gray-200 dark:border-gray-800">
//           <div className="p-4">
//             <form className="flex space-x-2">
//               <Input className="flex-1 min-w-0" placeholder="Type a message" />
//               <Button type="submit">Send</Button>
//             </form>
//           </div>
//         </div>
//       </div>
//     </div>
//   )
// }
